import { Router } from "express";
import multer from "multer";
const router = Router();
import { googleAuthController } from "../../controllers/v1/google-auth.controller.js";
import { chatController } from "../../controllers/v1/chat.controller.js";
import { authController } from "../../controllers/v1/auth.controller.js";
import { appointmentController } from "../../controllers/v1/appointment.controller.js";
const upload = multer({ storage: multer.memoryStorage() });
router.post("/auth/register", authController.register);
router.post("/auth/login", authController.login);
router.get("/auth/google", googleAuthController.getAuthUrl);
router.get("/auth/google/callback", googleAuthController.callback);
router.get("/auth/status", authController.getStatus);
router.post("/chat",upload.single("image"), chatController.handleChat);
router.get("/appointments", appointmentController.getAppointments);
export default router;